version: '3'
services:
  email-service.local:
    tty: true
    stdin_open: true
    container_name: email-service
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/app
